spring:
  application:
    name: grouple
  mvc:
    servlet:
      path: /api
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
      validation-timeout: 5000

app:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
